# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-05 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("insert into tests_t1(n) select (random()*100)::integer from generate_series(1,10000000);"),
        migrations.RunSQL("insert into tests_t2(n) select (random()*100)::integer from generate_series(1,10000000);"),
        migrations.RunSQL("insert into tests_t3(n) select (random()*100)::integer from generate_series(1,10000000);"),
    ]
