# Generated by Django 2.0 on 2017-12-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_insert_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('start_time', models.FloatField(default=0)),
                ('end_time', models.FloatField(default=0)),
            ],
        ),
    ]
